FROM ubuntu:24.04

RUN apt-get update && apt-get install -y squid apache2-utils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 3128

ENTRYPOINT ["squid", "--foreground", "-f", "/etc/squid/squid.conf"]
